
WAV BellRide "BellRide.wav" 2
WAV BellTree "BellTree.wav" 2
WAV BongoRim "BongoRim.wav" 2
WAV Cabasa "Cabasa.wav" 2
WAV Castanet "Castanet.wav" 2
WAV ChinaCrash "ChinaCrash.wav" 2
WAV Clap "Clap.wav" 2
WAV Clave "Clave.wav" 2
WAV ClosedSlap "ClosedSlap.wav" 2
WAV CowBell "CowBell.wav" 2
WAV Crsh1 "Crsh1.wav" 2
WAV Crsh2 "Crsh2.wav" 2
WAV FlrStudio "FlrStudio.wav" 2
WAV GuiroDown "GuiroDown.wav" 2
WAV GuiroUp "GuiroUp.wav" 2
WAV Hi-HatClosed "Hi-HatClosed.wav" 2
WAV Hi-HatFoot "Hi-HatFoot.wav" 2
WAV Hi-HatHalf-Open "Hi-HatHalf-Open.wav" 2
WAV HiStudio "HiStudio.wav" 2
WAV HighAgogo "HighAgogo.wav" 2
WAV HighConga "HighConga.wav" 2
WAV HighQ "HighQ.wav" 2
WAV HighTimbale "HighTimbale.wav" 2
WAV HighWoodblock "HighWoodblock.wav" 2
WAV LongTaikoHit "LongTaikoHit.wav" 2
WAV LongWhistle "LongWhistle.wav" 2
WAV LowAgogo "LowAgogo.wav" 2
WAV LowBongo "LowBongo.wav" 2
WAV LowFlrStudio "LowFlrStudio.wav" 2
WAV LowStudio "LowStudio.wav" 2
WAV LowTimbale "LowTimbale.wav" 2
WAV LowTumba "LowTumba.wav" 2
WAV LowWoodblock "LowWoodblock.wav" 2
WAV Maracas "Maracas.wav" 2
WAV MdHiStudio "MdHiStudio.wav" 2
WAV MdStudio "MdStudio.wav" 2
WAV MetronomeBell "MetronomeBell.wav" 2
WAV MetronomeClick "MetronomeClick.wav" 2
WAV Piccolo1-1 "Piccolo1-1.wav" 2
WAV Piccolo1-2 "Piccolo1-2.wav" 2
WAV QuicaHi "QuicaHi.wav" 2
WAV QuicaLow "QuicaLow.wav" 2
WAV Ride1 "Ride1.wav" 2
WAV Ride2 "Ride2.wav" 2
WAV RimTap "RimTap.wav" 2
WAV ScratchPull "ScratchPull.wav" 2
WAV ScratchPush "ScratchPush.wav" 2
WAV ShortTaikoHit "ShortTaikoHit.wav" 2
WAV ShortWhistle "ShortWhistle.wav" 2
WAV Slap "Slap.wav" 2
WAV SleighBells "SleighBells.wav" 2
WAV SmallShaker "SmallShaker.wav" 2
WAV Snr1-1 "Snr1-1.wav" 2
WAV Snr1-2 "Snr1-2.wav" 2
WAV Snr2-1 "Snr2-1.wav" 2
WAV Snr2-2 "Snr2-2.wav" 2
WAV Splash "Splash.wav" 2
WAV SquareClick "SquareClick.wav" 2
WAV StdKick "StdKick.wav" 2
WAV StdKick1 "StdKick1.wav" 2
WAV StdKick2 "StdKick2.wav" 2
WAV StdKick3 "StdKick3.wav" 2
WAV StdKick4 "StdKick4.wav" 2
WAV StdKick5 "StdKick5.wav" 2
WAV StdKick6 "StdKick6.wav" 2
WAV StdKick7 "StdKick7.wav" 2
WAV StdSnr1 "StdSnr1.wav" 2
WAV StdSnr2 "StdSnr2.wav" 2
WAV Sticks "Sticks.wav" 2
WAV Tambourine "Tambourine.wav" 2
WAV Triangle "Triangle.wav" 2
WAV VibraSlap "VibraSlap.wav" 2
